#!/usr/bin/env node

/**
 * Walrus WebAssembly Loader
 *
 * Loads and executes a WebAssembly module generated by the Walrus compiler.
 *
 * Usage:
 *   node wasm_loader.js <input.wat|input.wasm>
 *
 * Supports both WAT (text format) and WASM (binary format) files.
 */

const fs = require('fs');
const path = require('path');
const { createRuntime } = require('./runtime_wasm.js');

/**
 * Load and execute a WebAssembly module
 * @param {string} inputPath - Path to .wat or .wasm file
 */
async function loadAndRun(inputPath) {
  if (!fs.existsSync(inputPath)) {
    console.error(`Error: File not found: ${inputPath}`);
    process.exit(1);
  }

  const ext = path.extname(inputPath).toLowerCase();
  let wasmBytes;

  if (ext === '.wat') {
    // WAT text format - need to convert to binary first
    // Try using wabt's wat2wasm if available, otherwise try WebAssembly.compile
    try {
      // Read WAT content
      const watContent = fs.readFileSync(inputPath, 'utf8');

      // Try to compile directly (Node.js 16+ supports WAT in some configurations)
      try {
        const module = await WebAssembly.compile(
          new TextEncoder().encode(watContent)
        );
        wasmBytes = module;
      } catch (e) {
        // Try using wat2wasm command-line tool
        const { execSync } = require('child_process');
        const tempWasm = inputPath.replace('.wat', '.temp.wasm');

        try {
          execSync(`wat2wasm "${inputPath}" -o "${tempWasm}"`, { stdio: 'pipe' });
          wasmBytes = fs.readFileSync(tempWasm);
          fs.unlinkSync(tempWasm); // Clean up temp file
        } catch (wat2wasmError) {
          console.error('Error: Could not compile WAT file.');
          console.error('Please install wabt: npm install -g wabt');
          console.error('Or convert to .wasm binary format first.');
          console.error(`\nWAT compilation error: ${wat2wasmError.message}`);
          process.exit(1);
        }
      }
    } catch (readError) {
      console.error(`Error reading file: ${readError.message}`);
      process.exit(1);
    }
  } else if (ext === '.wasm') {
    // Binary WASM format - read directly
    wasmBytes = fs.readFileSync(inputPath);
  } else {
    console.error(`Error: Unsupported file extension: ${ext}`);
    console.error('Supported formats: .wat (text), .wasm (binary)');
    process.exit(1);
  }

  // Create runtime imports
  const imports = createRuntime();

  try {
    // Instantiate the WebAssembly module
    let instance;

    if (wasmBytes instanceof WebAssembly.Module) {
      instance = await WebAssembly.instantiate(wasmBytes, imports);
    } else {
      const result = await WebAssembly.instantiate(wasmBytes, imports);
      instance = result.instance;
    }

    // Look for and run main function
    const exports = instance.exports;

    if (typeof exports.main === 'function') {
      const startTime = performance.now();
      const result = exports.main();
      const endTime = performance.now();

      console.log(`\n--- Execution completed ---`);
      console.log(`Return value: ${result}`);
      console.log(`Time: ${(endTime - startTime).toFixed(2)}ms`);
    } else if (typeof exports._start === 'function') {
      // WASI-style entry point
      exports._start();
    } else {
      console.log('Available exports:', Object.keys(exports));
      console.error('Error: No main or _start function found in module');
      process.exit(1);
    }
  } catch (instantiateError) {
    console.error(`Error instantiating WebAssembly module: ${instantiateError.message}`);

    if (instantiateError.message.includes('import')) {
      console.error('\nThis may be due to missing imports. Check that all required');
      console.error('runtime functions are provided.');
    }

    process.exit(1);
  }
}

// Main entry point
const args = process.argv.slice(2);

if (args.length === 0) {
  console.log('Walrus WebAssembly Loader');
  console.log('');
  console.log('Usage: node wasm_loader.js <input.wat|input.wasm>');
  console.log('');
  console.log('Options:');
  console.log('  -h, --help    Show this help message');
  process.exit(0);
}

if (args[0] === '-h' || args[0] === '--help') {
  console.log('Walrus WebAssembly Loader');
  console.log('');
  console.log('Loads and executes WebAssembly modules generated by the Walrus compiler.');
  console.log('');
  console.log('Usage: node wasm_loader.js <input.wat|input.wasm>');
  console.log('');
  console.log('Supported formats:');
  console.log('  .wat   WebAssembly Text format (requires wabt for conversion)');
  console.log('  .wasm  WebAssembly Binary format');
  console.log('');
  console.log('Examples:');
  console.log('  node wasm_loader.js program.wat');
  console.log('  node wasm_loader.js program.wasm');
  process.exit(0);
}

loadAndRun(args[0]).catch((error) => {
  console.error(`Unexpected error: ${error.message}`);
  process.exit(1);
});
